apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    'quay.io/repository-slug': esapram/docker-node-app
    'backstage.io/kubernetes-id': test-app
    'janus-idp.io/tekton': test-app
    'argocd/app-selector': quarkus-app-bootstrap
  name: test-backstage-application
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
