apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    'backstage.io/techdocs-ref': dir:.
    'quay.io/repository-slug': esapram/docker-node-app
    'backstage.io/kubernetes-id': test-app
    'janus-idp.io/tekton': test-app
    'argocd/app-selector': rht-gitops.com/janus-argocd=quarkus-app-bootstrap
    # 'argocd/app-name': quarkus-app
    'github.com/project-slug': 'Eswaraiahsapram/GHA-matrix-workflow'
    'jenkins.io/job-full-name': 'calculator-app-pipeline'
    'dev.azure.com/project-repo': my-project/my-repo
    'github.com/project-slug': redhat-developer/rhdh-plugins
  name: rhdh-app
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
