apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    'quay.io/repository-slug': esapram/docker-node-app
  name: test-backstage-application
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
