apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website-invalid
  annotations:
    # github.com/project-slug: redhat-developer/rhdh-plugins
    # backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins
    jira/project-key: RHDHBUGS
    # scorecard.io/github.open-prs.thresholds.rules.warning: '10--15'
    # scorecard.io/jira.open-issues.thresholds.rules.warning: '10--15'
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
