---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Eswaraiahsapram
spec:
  profile:
    # Intentional no displayName for testing
    email: esapram@redhat.com
    displayName: Eswar S
  memberOf: [temp-team-a]
